### ISSUE TITLE
1.1.0 Version Mismatch?

### ISSUE THREAD

**Issue by damassi** [nodkz/react-relay-network-modern-ssr#4]
I think something odd happened during last publish, or there's an issue with NPM:

On [NPM page](https://www.npmjs.com/package/react-relay-network-modern-ssr) it reads correctly: 

<img width="404" alt="screen shot 2018-05-22 at 11 59 11 am" src="https://user-images.githubusercontent.com/236943/40384118-8ec3c886-5db7-11e8-9946-dbb084f9ecaf.png">

But when installing, it can't find it:

![screen shot 2018-05-22 at 11 57 55 am](https://user-images.githubusercontent.com/236943/40384137-98d86c14-5db7-11e8-9783-e8949d91e2fb.png)

With `yarn info react-relay-network-modern-ssr` returning: 

![screen shot 2018-05-22 at 12 00 07 pm](https://user-images.githubusercontent.com/236943/40384174-b318bbc4-5db7-11e8-8d9f-871ca8cf8118.png)

Thoughts?

**Comment by nodkz** [comment]
It's npm very rare problem. For the last 2 years I have met such a problem only once.

Published new 1.1.1 version.

**Comment by damassi** [comment]
👍
